name: Christina Lake
favicon: null
layout_spectrum: 1
typography_spectrum: 0.085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#114884'
    - '#5bb1e3'
    - '#00ffff'
    - '#00ff00'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
